# -*- mode: ruby -*-
# vi: set ft=ruby :
required_plugins = %w( vagrant-hostmanager vagrant-hosts-provisioner )
required_plugins.each do |plugin|
  system "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
end

Vagrant.configure("2") do |config|
  #config.vm.provision :shell, :inline => "sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config; sudo systemctl restart sshd;", run: "always"
  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box = "geerlingguy/centos7"
    #jenkins.vm.network "private_network", type: "dhcp"
    #jenkins.vm.network "private_network", ip: "192.168.100.100", netmask: "255.255.255.0", network_name: "mynetwork"
    jenkins.vm.network "private_network", ip: "10.0.0.10"
    jenkins.vm.hostname = "jenkins"
    jenkins.vm.provider "virtualbox" do |v|
      v.name = "jenkins"
      v.memory = 2048
      v.cpus = 2
    end
    jenkins.vm.provision :shell do |shell|
      shell.path = "install_jenkins.sh"
    end
    jenkins.vm.provision :shell do |shell|
      shell.inline = <<-SHELL
        docker exec -i jenkins sh -c 'cat /var/jenkins_home/secrets/initialAdminPassword'
      SHELL
    end
  end
end
