# This guide is optimized for Vagrant 1.8 and above.
# Older versions of Vagrant put less info in the inventory they generate.
Vagrant.require_version ">= 1.8.0"

RAM = 4096
CPU = 1
IP = "10.0.0.11"

Vagrant.configure("2") do |config|
  config.vm.define "ansible_managednode" do |ansiblemn|
    ansiblemn.vm.box = "boxomatic/centos-stream-9" #With Vitualbox Guest Additions
    #config.ssh.username = "doudou"
    #config.ssh.insert_key = true
    ansiblemn.vm.network "private_network", ip: IP
    ansiblemn.vm.hostname = "ansiblemn"
    #config.vm.synced_folder "static-website-example/", "/usr/share/nginx/html/"
    ansiblemn.vm.provider "virtualbox" do |v|
      v.name = "ansiblemn"
      v.memory = RAM
      v.cpus = CPU
    end
    ansiblemn.vm.provision :shell do |shell|
      shell.path = "install_ansible.sh"
    end
    # config.vm.provision "ansible" do |ansible|
    #   ansible.verbose = "v"
    #   ansible.playbook = "playbook.yml"
    # end
  end
end
